### ISSUE TITLE
iOS target for Carthage

### ISSUE THREAD

**Issue by ollitapa** [pointfreeco/swift-overture#27]
I know, SwiftPM does not support iOS yet, but do you want to support it for Carthage?

Currently Carthage works fine until one tries to create an archive and distribute it. Builds work and run on device via Xcode. When converting archive using bitcode option I get this odd error:

```
 warning: Failed to resolve linkage dependency Overture arm64 -> @rpath/libswiftCore.dylib: Could not find MachO for /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
```
Somehow Overture tries to link to macosx libs of Swift. I was able to resolve this by manually making a separate iOS framework target to the xcodeproj. Not an optimal solution. Any ideas?

**Comment by stephencelis** [comment]
This should be fixed as of #32. Can you confirm and close if so?

**Comment by ollitapa** [comment]
Still got this kind of error: "Failed to load Info.plist from bundle at path ..."
I added Info.plist generation to the /project.yml and it seems to work!

**Comment by stephencelis** [comment]
Fixed by #35! Thanks again!

**Comment by mdarnall** [comment]
@stephencelis Hi, thanks for this library and your work on Pointfree (i'm a happy subscriber). Just FYI this bug hit us recently because I didn't notice the latest release didn't include this fix. Taking `master` with carthage fixed it though.

**Comment by stephencelis** [comment]
@mdarnall Sorry about that! We just cut 0.4.0.
