### ISSUE TITLE
Ambiguous use of `with`

### ISSUE THREAD

**Issue by pteasima** [pointfreeco/swift-overture#30]
on latest version (xcode 10.1, Swift4.2, Overture 0.3.1), even the basic example from your readme fails:
```
import Overture
class MyViewController: UIViewController {
    let label = with(UILabel()) {
        $0.font = .systemFont(ofSize: 24)
        $0.textColor = .red
    }
}
```
I think theres ambiguity between the standard and inout versions of with. I would have to annotate the type, e.g `let with(UILabel) { (l: inout UILabel) in ...}` to fix it.

But its such an obvious issue, Im sure you or others must have seen it. Any suggestions?

**Comment by pteasima** [comment]
Or maybe you never saw it cause you're using `with` with `set` or `mut`, but I have to think of the newbies ;)

**Comment by stephencelis** [comment]
I think this snuck in with a Swift update :( We need to most likely get rid of one of the conflicting overloads.
