### ISSUE TITLE
Redefine `set` without `over`

### ISSUE THREAD

**Issue by stephencelis** [pointfreeco/swift-overture#31]
While it's really nice that `set` can be derived from `over`, the implicit key-path `get` is not only doing extra work, but can crash when dealing with implicitly-unwrapped optionals.

``` swift
let formatter = NumberFormatter()
formatter.locale = Locale(identifier: "")
with(formatter, set(\.currencyCode, "USD"))
// crash due to `currencyCode` being a `String!`
```

We should redefine our setters to not leverage `over`.

**Comment by mbrandonw** [comment]
Closing this cause it turns out it's just IUO's not playing nicely with key paths more generally: https://bugs.swift.org/browse/SR-9478
