### ISSUE TITLE
Compile times of with, concat & mut functions in swift4 are very high!!

### ISSUE THREAD

**Issue by jonchui** [pointfreeco/swift-overture#40]
I inherited some code, and compile time was crazy (90s - 120s, incremental. 3.5 min new) . So i ran 
https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode

on our codebase and all the functions or `lazy vars` that used `concat`, `mut`, `with` from swift overture were taking considerable time to compile. 

For ex. this `stackview` getter was taking >5 seconds to compile!!!!

```
var stackView = with(UIStackView(), concat(
        mut(\.axis, .vertical),
        mut(\.isLayoutMarginsRelativeArrangement, true),
        mut(\.layoutMargins, UIEdgeInsets(top: 0, left: 16, bottom: 0, right: 16)),
        mut(\.spacing, 16),
        mut(\.alignment, .center)
    ))
```
Some other examples:

```
var titleLabel: UILabel = with(UILabel(), concat(
        autolayoutStyle,
        mut(\.font, .sg_font(size: 24, weight: .bold)),
        mut(\.textAlignment, .center),
        mut(\.numberOfLines, 0),
        mut(\.lineBreakMode, .byWordWrapping)
        )
    )

    var promptLabel: UILabel = with(UILabel(), concat(
        autolayoutStyle,
        mut(\.font, .sg_font(size: 14, weight: .regular)),
        mut(\.textAlignment, .center),
        mut(\.numberOfLines, 0),
        mut(\.lineBreakMode, .byWordWrapping)
        )
    )

    var stackView: UIStackView = with(UIStackView(), concat(
        autolayoutStyle,
        mut(\.axis, .vertical),
        mut(\.spacing, 7),
        mut(\.isLayoutMarginsRelativeArrangement, true),
        mut(\.layoutMargins, .init(top: 29, left: 16, bottom: 27, right: 16))
        )
    )
```

As this is a new framework/library for me, I'd love to hear if I'm the only one experiencing this?

**Comment by stephencelis** [comment]
This is mainly an issue of key paths taking longer when not qualified. Try recompiling `stackView` by qualifying at least one of the root types:

``` swift
var stackView = with(UIStackView(), concat(
    mut(\UIStackView.axis, .vertical),
    mut(\.isLayoutMarginsRelativeArrangement, true),
    mut(\.layoutMargins, UIEdgeInsets(top: 0, left: 16, bottom: 0, right: 16)),
    mut(\.spacing, 16),
    mut(\.alignment, .center)
))
```

You can go so far as to qualify _all_ root types to get a massive speedup:

``` swift
var stackView = with(UIStackView(), concat(
    mut(\UIStackView.axis, .vertical),
    mut(\UIStackView.isLayoutMarginsRelativeArrangement, true),
    mut(\UIStackView.layoutMargins, UIEdgeInsets(top: 0, left: 16, bottom: 0, right: 16)),
    mut(\UIStackView.spacing, 16),
    mut(\UIStackView.alignment, .center)
))
```

I think this is worth filing a bug at bugs.swift.org, though, as they should be able to make some optimizations here.

**Comment by mbrandonw** [comment]
Hey @jonchui, we're going to close this out, but it's definitely an issue. One thing you could also try is to not use `lazy`, which tends to put a lot of pressure on the type checker. Usually the way `lazy` is used is not really saving too much work since most of a view's properties are probably accessed immediately.

Also filing bugs at bugs.swift.org can always help. The type checker has definitely gotten better over the years and these use cases provide great real-world examples.
