### ISSUE TITLE
Add @discardableResult to update()

### ISSUE THREAD

**Issue by ferologics** [pointfreeco/swift-overture#60]
Currently `@discardableResult` is set on the `AnyObject` update methods. I think having `@discardableResult` everywhere would would clear up the warnings `result of call 'update' is not used`:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/5576161/98217637-0ca3c600-1f4b-11eb-9542-fe493af23a5e.png">

WDYT?

**Comment by ferologics** [comment]
There's quite a few of them <img width="293" alt="image" src="https://user-images.githubusercontent.com/5576161/98224740-2269b900-1f54-11eb-92e0-4130e4bd7dcf.png">

**Comment by ferologics** [comment]
I can make the warnings go away by prefixing the variable passed into the function parameter with an `&`. This is a bit strange API.

**Comment by stephencelis** [comment]
@ferologics Sorry for the delay. This is intentional because these `update` functions _copy_ the underlying value and return a result and do _not_ mutate value types in-place. Without the warning the operation would be a no-op, since the transformed value would be discarded.

**Comment by stephencelis** [comment]
Closing for now, just so you don't feel the need to do so yourself, but if I've missed anything, please let me know and I'll reopen!
