### ISSUE TITLE
Throwing overloads

### ISSUE THREAD

**Issue by vknabel** [pointfreeco/swift-overture#9]
First of all: thank you for your great work!

Currently there are no overloads for `chain`, `compose`, `pipe`, `concat`, ... that work with throwing functions.

If you want, I can open a PR that adds these overloads.

**Comment by stephencelis** [comment]
This sounds reasonable to me! We'd def take a PR for this.

**Comment by stephencelis** [comment]
Hm, one consideration is composing throwing functions with non-throwing functions, which wouldn't be scalable with overloads.

``` swift
pipe((A) throws -> B, (B) -> C)
// (A) throws -> C
```

So we'd probably want a way to "cast" non-throwing functions into throwing ones for the sake of composition. Something like:

``` swift
pipe((A) throws -> B, throwing((B) -> C))
// (A) throws -> C
```

We typically compose with types, and `throws` complicates this. So one alternative direction to consider would be to introduce a `Result` or `Either` type with which we can convert between the throwing and non-throwing world.

``` swift
unthrow((A) throws -> B) -> (A) -> Either<Error, B>
throwing((A) -> Either<Error, B>) -> (A) throws -> B
```

Not sure what direction we wanna go here...so maybe hold off on that PR after all, sorry!

**Comment by vknabel** [comment]
I already played a bit around with this and defined a throwing chain3 in a playground.
As Swift allows non-optionals to be passed as optionals, it also allows non-throwing functions to be passed as a throwing function.

Below an example usage directly copied from my playground. The non-throwing chain3 can still be used without any problems. In this case they were defined on `([T], A)` as I was experimenting with an arguments parser for CLIs.

```swift
func chain<Element, A, B, C>(
    _ f: @escaping ([Element]) throws -> ([Element], A),
    _ g: @escaping ([Element]) throws -> ([Element], B),
    _ h: @escaping ([Element]) throws -> ([Element], C)
) -> ([Element]) throws -> (A, B, C)

let (isVerbose, whoToGreet, _) = try with(["-v", "hi"], chain(
    flag("verbose", "v"), // does not throw
    argument(named: "Name"), // throws
    exhaust // throws
))
```

**Comment by stephencelis** [comment]
Oh nice! If that's the case and there are no conflicts, then I'm good with overloads!
